// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const cloneElement: typeof import('react')['cloneElement']
  const createElement: typeof import('react')['createElement']
  const isValidElement: typeof import('react')['isValidElement']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
export {}
